"""add sample_html and url and meta to alerts

Revision ID: 06bf43d58981
Revises: 3ffd8d3fc203
Create Date: 2025-09-13 10:06:04.034562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06bf43d58981'
down_revision: Union[str, Sequence[str], None] = '3ffd8d3fc203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('futbin_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('meta', sa.String(), nullable=True))
        batch_op.drop_column('sample_meta')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sample_meta', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('meta')
        batch_op.drop_column('futbin_url')

    # ### end Alembic commands ###
