"""change settings

Revision ID: 9fa75d201a59
Revises: aa1a6b9f8f62
Create Date: 2025-08-05 09:55:29.135142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fa75d201a59'
down_revision: Union[str, Sequence[str], None] = 'aa1a6b9f8f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playercards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_bid_price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('min_bid_price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_buy_now_price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('min_buy_now_price', sa.Integer(), nullable=True))
        batch_op.drop_column('buy_now_price')
        batch_op.drop_column('bid_price')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('is_successful',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('is_settled',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('customer_phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('customer_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('transfer_multiplier',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('transfer_multiplier',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('customer_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('customer_phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('is_settled',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('is_successful',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('playercards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bid_price', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('buy_now_price', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('min_buy_now_price')
        batch_op.drop_column('max_buy_now_price')
        batch_op.drop_column('min_bid_price')
        batch_op.drop_column('max_bid_price')

    # ### end Alembic commands ###
