"""add CardRangeAssignment model

Revision ID: a135a88c8674
Revises: b74ed5395d46
Create Date: 2025-07-22 10:08:06.886531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a135a88c8674'
down_revision: Union[str, Sequence[str], None] = 'b74ed5395d46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_settings_id'), table_name='transfer_settings')
    op.drop_table('transfer_settings')
    op.drop_index(op.f('ix_transfer_card_rules_id'), table_name='transfer_card_rules')
    op.drop_table('transfer_card_rules')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_card_rules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('card_range_id', sa.INTEGER(), nullable=False),
    sa.Column('primary_card_id', sa.INTEGER(), nullable=False),
    sa.Column('fallback_card_id', sa.INTEGER(), nullable=True),
    sa.Column('platform', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['card_range_id'], ['card_ranges.id'], ),
    sa.ForeignKeyConstraint(['fallback_card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['primary_card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_card_rules_id'), 'transfer_card_rules', ['id'], unique=False)
    op.create_table('transfer_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('threshold_amount', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_settings_id'), 'transfer_settings', ['id'], unique=False)
    # ### end Alembic commands ###
