"""change

Revision ID: aa1a6b9f8f62
Revises: 619a012a40b0
Create Date: 2025-08-05 09:45:02.118204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa1a6b9f8f62'
down_revision: Union[str, Sequence[str], None] = '619a012a40b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('transactions', 'timestamp',
    #            existing_type=sa.DATETIME(),
    #            nullable=False)
    # op.alter_column('transactions', 'is_successful',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # op.alter_column('transactions', 'is_settled',
    #            existing_type=sa.INTEGER(),
    #            nullable=False)
    # op.alter_column('transactions', 'customer_phone',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.alter_column('transactions', 'customer_email',
    #            existing_type=sa.VARCHAR(),
    #            nullable=False)
    # op.alter_column('transactions', 'transfer_multiplier',
    #            existing_type=sa.FLOAT(),
    #            nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('transactions', 'transfer_multiplier',
    #            existing_type=sa.FLOAT(),
    #            nullable=True)
    # op.alter_column('transactions', 'customer_email',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # op.alter_column('transactions', 'customer_phone',
    #            existing_type=sa.VARCHAR(),
    #            nullable=True)
    # op.alter_column('transactions', 'is_settled',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # op.alter_column('transactions', 'is_successful',
    #            existing_type=sa.INTEGER(),
    #            nullable=True)
    # op.alter_column('transactions', 'timestamp',
    #            existing_type=sa.DATETIME(),
    #            nullable=True)
    # ### end Alembic commands ###
