"""transfer_method:model,route,crud added multiplier count

Revision ID: e32241da9561
Revises: 5b386ae55006
Create Date: 2025-08-20 10:29:10.133762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e32241da9561'
down_revision: Union[str, Sequence[str], None] = '5b386ae55006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfer_methods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transfer_multiplier', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfer_methods', schema=None) as batch_op:
        batch_op.drop_column('transfer_multiplier')

    # ### end Alembic commands ###
