"""add sample_html and url and meta to alerts

Revision ID: e63816b6c481
Revises: 06bf43d58981
Create Date: 2025-09-14 00:15:16.037103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'e63816b6c481'
down_revision: Union[str, Sequence[str], None] = '06bf43d58981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_cache_id'))
        batch_op.drop_index(batch_op.f('ix_price_cache_player_id'))

    op.drop_table('price_cache')
    with op.batch_alter_table('transfer_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfer_tasks_id'))

    op.drop_table('transfer_tasks')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.create_table('transfer_tasks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ea_account_id', sa.INTEGER(), nullable=False),
    sa.Column('player_id', sa.VARCHAR(), nullable=False),
    sa.Column('max_price', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), nullable=False),
    sa.Column('attempts', sa.INTEGER(), nullable=False),
    sa.Column('last_error', sa.VARCHAR(), nullable=True),
    sa.Column('meta', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['ea_account_id'], ['ea_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transfer_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfer_tasks_id'), ['id'], unique=False)

    op.create_table('price_cache',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('player_id', sa.VARCHAR(), nullable=False),
    sa.Column('platform', sa.VARCHAR(), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('currency', sa.VARCHAR(), nullable=True),
    sa.Column('fetched_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_cache_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_cache_id'), ['id'], unique=False)

    # ### end Alembic commands ###
