"""Fix relationships

Revision ID: f1c8c960deca
Revises: 
Create Date: 2025-07-24 07:35:53.654974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1c8c960deca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buy_price', sa.Float(), nullable=False),
    sa.Column('sell_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_prices_id'), 'admin_prices', ['id'], unique=False)
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_table('playercards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('club', sa.String(), nullable=True),
    sa.Column('nation', sa.String(), nullable=True),
    sa.Column('league', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('chemistry', sa.Integer(), nullable=True),
    sa.Column('is_special', sa.Boolean(), nullable=True),
    sa.Column('bid_price', sa.Float(), nullable=True),
    sa.Column('buy_now_price', sa.Float(), nullable=True),
    sa.Column('last_sale_price', sa.Float(), nullable=True),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('price_range_min', sa.Float(), nullable=True),
    sa.Column('price_range_max', sa.Float(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=True),
    sa.Column('owner_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playercards_id'), 'playercards', ['id'], unique=False)
    op.create_table('transfer_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('logic', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_transfer_methods_id'), 'transfer_methods', ['id'], unique=False)
    op.create_table('card_ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=False),
    sa.Column('max_value', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('transfer_method_id', sa.Integer(), nullable=False),
    sa.Column('primary_card_id', sa.Integer(), nullable=True),
    sa.Column('fallback_card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fallback_card_id'], ['playercards.id'], ),
    sa.ForeignKeyConstraint(['primary_card_id'], ['playercards.id'], ),
    sa.ForeignKeyConstraint(['transfer_method_id'], ['transfer_methods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_ranges_id'), 'card_ranges', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['playercards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_card_ranges_id'), table_name='card_ranges')
    op.drop_table('card_ranges')
    op.drop_index(op.f('ix_transfer_methods_id'), table_name='transfer_methods')
    op.drop_table('transfer_methods')
    op.drop_index(op.f('ix_playercards_id'), table_name='playercards')
    op.drop_table('playercards')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')
    op.drop_index(op.f('ix_admin_prices_id'), table_name='admin_prices')
    op.drop_table('admin_prices')
    # ### end Alembic commands ###
